### ISSUE TITLE
Ruby Version Compatability?

### ISSUE THREAD

**Issue by whatisdot** [bodyshopbidsdotcom/snap-style#5]
This was uncovered when trying to add snap-style to `infra`: https://github.com/bodyshopbidsdotcom/infra/pull/86

I followed the default instructions to add the gem to our project. One exception is that I had to add the git url in the Gemfile:
```ruby
gem 'snap-style', git: 'https://[REDACTED]:x-oauth-basic@github.com/bodyshopbidsdotcom/snap-style.git', tag: 'v2.0.0'
```

After doing this, gem installs without issue. However the rubocop command fails:
```
Unable to find gem snap-style; is the gem installed? Gem::MissingSpecError
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/config_loader_resolver.rb:204:in `rescue in gem_config_path'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/config_loader_resolver.rb:200:in `gem_config_path'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/config_loader_resolver.rb:56:in `block (2 levels) in resolve_inheritance_from_gems'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/config_loader_resolver.rb:54:in `reverse_each'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/config_loader_resolver.rb:54:in `block in resolve_inheritance_from_gems'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/config_loader_resolver.rb:47:in `each_pair'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/config_loader_resolver.rb:47:in `resolve_inheritance_from_gems'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/config_loader.rb:49:in `load_file'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/config_loader.rb:86:in `configuration_from_file'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/config_store.rb:44:in `for'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/cli.rb:242:in `apply_default_formatter'
/usr/local/bundle/gems/rubocop-0.71.0/lib/rubocop/cli.rb:50:in `run'
/usr/local/bundle/gems/rubocop-0.71.0/exe/rubocop:13:in `block in <top (required)>'
/usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/gems/rubocop-0.71.0/exe/rubocop:12:in `<top (required)>'
/usr/local/bundle/bin/rubocop:23:in `load'
/usr/local/bundle/bin/rubocop:23:in `<main>'
```

I noticed the Rubocop version tagged in snap-style is `0.52.1`. The version we are using is `0.71.0`. At some point when trying to get the old version to work, I got this error (unable to reproduce):
```
Error: Unknown Ruby version 2.6 found in `.ruby-version`.
Supported versions: 2.1, 2.2, 2.3, 2.4, 2.5
```

Our project is using Ruby v2.6.3

**Comment by santi-h** [comment]
@whatisdot this is locking version `0.52.1` because [that's the version codeclimate uses](https://docs.codeclimate.com/docs/rubocop). If you use a version different than the one in codeclimate, you end up with issues that codeclimate flags but cannot be reproduced anywhere else. Also it wouldn't be able to understand certain things in the config file.

**Comment by rshejnberg** [comment]
@whatisdot did you discover a workaround for this have a new app using `2.7.0` and running into this same issue

**Comment by whatisdot** [comment]
As a result of this issue, we had to remove `snap-style` as a requirement for this project, and manually added the Rubocop configuration: https://github.com/bodyshopbidsdotcom/infra/blob/master/.rubocop.yml

**Comment by rshejnberg** [comment]
gotcha, looks like we'll do the same, thanks

**Comment by susannah-go** [comment]
Hi. Not to alarm anybody, but I just got an email notification about these comments, and it appears that I still have at least some of my Snapsheet GitHub access.
